name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${{ env.PASSWORD }}"
      - run: echo "${{ env.PASSWORD:0:1 }} ${{ env.PASSWORD#? }}"
